package com.otectus.runic_races.registry;

import com.otectus.runic_races.RunicRacesMod;
import net.minecraft.core.particles.ParticleType;
import net.minecraft.core.particles.SimpleParticleType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * Custom race-identity particles. Registration is common-side (the registry is synced);
 * only the sprite providers in {@code client/particle} are client-only.
 *
 * Sprite sheets are generated by {@code tools/generate_particles.py} into
 * {@code textures/particle/} — bespoke art can replace them without code changes.
 */
public class ModParticles {

    public static final DeferredRegister<ParticleType<?>> PARTICLES =
            DeferredRegister.create(ForgeRegistries.PARTICLE_TYPES, RunicRacesMod.MOD_ID);

    /** Floating runic glyph — Runic One ward zones, Forge Blessing accents. */
    public static final RegistryObject<SimpleParticleType> RUNE_GLYPH = register("rune_glyph");
    /** Drifting soul flame — Reaper revival/harvest, Wraith phase trail, friendly-summon marking. */
    public static final RegistryObject<SimpleParticleType> SOUL_WISP = register("soul_wisp");
    /** Gossamer shimmer — Sprite/Faerie wing flutter, Faerie Bargain glamour. */
    public static final RegistryObject<SimpleParticleType> FAE_SPARKLE = register("fae_sparkle");
    /** Drifting ember flake — Fire Drake breath accent, Demon Infernal Wrath. */
    public static final RegistryObject<SimpleParticleType> EMBER_SCALE = register("ember_scale");
    /** Crystalline rime mote — Ice Elf frost (distinct from Ice Drake's snowflake cone). */
    public static final RegistryObject<SimpleParticleType> FROST_MOTE = register("frost_mote");
    /** Venom droplet — Arachnid and Serpen venom procs. */
    public static final RegistryObject<SimpleParticleType> VENOM_DRIP = register("venom_drip");

    private static RegistryObject<SimpleParticleType> register(String name) {
        return PARTICLES.register(name, () -> new SimpleParticleType(false));
    }

    public static void register(IEventBus modBus) {
        PARTICLES.register(modBus);
    }
}
