"""1.7.0 authoring inputs. Values emitted into Apoli powers are the runtime tuning source."""

RACES = [
    dict(id="colossan", family="human", display="Colossan", scale=1.20, feathers=26, impact=2, ars=(1,1), iss=1,
         powers=("colossal_heave","giants_bearing","heavy_limbs"), names=("Colossal Heave","Giant's Bearing","Heavy Limbs"), cd=700, duration=100,
         lore="Giant-descended mortals who measure strength in the weight of a single promise. Their blows arrive slowly, and leave a lasting impression.",
         active="Prepare one direct melee strike for {duration}s. At 90% attack charge, the next successful primary hit adds 3 HP of physical damage and moderate knockback. Sweeping hits do not consume or repeat it.",
         passive="+4 maximum HP and +0.30 knockback resistance. With Pehkui, stand at 1.20 scale; this grants no racial reach bonus.",
         weakness="-12% attack speed and +15% exhaustion. Time your swings and carry a good meal.",
         params=dict(bonus=3,min_charge=.9), attrs_p=dict(health=4,kb=.30), attrs_w=dict(attack_speed=-.12), exhaustion=.15),
    dict(id="auroran", family="human", display="Auroran", scale=1.02, feathers=18, impact=2, ars=(1.10,.95), iss=1.05,
         powers=("dawnward","inner_radiance","mortal_vessel"), names=("Dawnward","Inner Radiance","Mortal Vessel"), cd=1100,duration=120,
         lore="A quiet sunrise lives in these mortal souls. Aurorans shelter their companions with brief, carefully shared light.",
         active="Ward yourself and up to two allies within 6 blocks and clear sight for {duration}s. Each ward prevents at most 4 HP after armor and absorption. Racial wards never add together on one hit.",
         passive="+2 maximum HP and 15% less classified magical damage. A magical projectile uses this affinity.",
         weakness="Take 15% more ordinary physical and projectile damage. Armor, shields and cover remain useful; magical projectiles do not also receive this penalty.",
         params=dict(budget=4,prevent_fraction=1,range=6,targets=3),attrs_p=dict(health=2), traits_p=dict(magic_reduction=.15),traits_w=dict(physical_extra=.15)),
    dict(id="grove_elf",family="elven",display="Grove Elf",scale=1.06,feathers=20,impact=1,ars=(1.1,.92),iss=1,
         powers=("stillleaf_aim","canopy_strider","slender_frame"),names=("Stillleaf Aim","Canopy Strider","Slender Frame"),cd=700,duration=120,
         lore="Woodland travelers who learn the wind before drawing a bow. Stillness, a clear sightline, and one patient arrow are their chosen tools.",
         active="For {duration}s, prepare one fully drawn bow or loaded crossbow arrow. Its first successful hit gains 20% damage, capped at +2 HP. For 3s, only you see a small target cue while it remains visible. Multishot empowers one arrow; Piercing cannot repeat the bonus.",
         passive="+10% grounded speed in forest-tagged biomes. Tagged berry underbrush does not slow you; sweet berry bush damage is harmless. Leaves and webs still obstruct you.",
         weakness="-3 maximum HP. Choose cover and distance before committing to a shot.",
         params=dict(fraction=.2,bonus=2,effect_ticks=60),traits_p=dict(forest_speed=.10),attrs_w=dict(health=-3)),
    dict(id="tide_elf",family="elven",display="Tide Elf",scale=1.04,feathers=20,impact=2,ars=(1.1,.92),iss=1,
         powers=("currentstep","amphibious_grace","drying_gills"),names=("Currentstep","Amphibious Grace","Drying Gills"),cd=500,duration=10,
         lore="Coastal elves at home where sunlight breaks into currents. Their hands work as naturally beneath the water as upon the shore.",
         active="Travel up to 5 blocks through water over {duration}s, following your aim. On land, take a 2-block grounded step. Solid obstacles stop the movement; the current deals no damage.",
         passive="Breathe water, swim 20% faster, see clearly underwater, and remove the normal underwater mining penalty. Tool tiers, Aqua Affinity and Mining Fatigue still work normally. Jump to rise; release jump or sneak to descend.",
         weakness="-2 maximum HP. After 60s out of water or rain, move 8% slower. One second in water, rain exposure, or drinking a potion or water bottle refreshes your gills.",
         params=dict(range=5,land_range=2,move_ticks=10),traits_p=dict(swim_speed=.2),traits_w=dict(dry_after=1200,wet_refresh=20,dry_slow=.08),attrs_w=dict(health=-2),water=True,water_vision=True),
    dict(id="astral_elf",family="elven",display="Astral Elf",scale=1.07,feathers=16,impact=2,ars=(1.15,.9),iss=1.05,
         powers=("starbound_thread","astral_poise","thin_tether"),names=("Starbound Thread","Astral Poise","Thin Tether"),cd=800,duration=160,
         lore="Star-minded wanderers who leave a thread behind each daring step. Their gift remembers a safe beginning, never an unknown destination.",
         active="Place a safe grounded anchor for {duration}s. Release and press again to return within 16 blocks in the same dimension, with clear sight and safe footing. Cooldown begins on placement. Blocked recall leaves the anchor until expiry.",
         passive="Take 30% less fall damage. Gain night vision during actual nighttime in dimensions with a normal day/night cycle.",
         weakness="-3 maximum HP. A fragile tether cannot cross walls, dimensions or distant terrain; plan an escape before danger arrives.",
         params=dict(range=16),traits_p=dict(fall_reduction=.3),attrs_w=dict(health=-3),vision="night"),
    dict(id="mountain_one",family="dwarven",display="Mountain One",scale=.76,feathers=26,impact=1,ars=(.9,1),iss=1,
         powers=("quarry_rhythm","bedrock_bearing","deliberate_gait"),names=("Quarry Rhythm","Bedrock Bearing","Deliberate Gait"),cd=900,duration=120,
         lore="Stoneworkers who hear a measured rhythm in the mountains. Their craft is patient excavation, one honest block at a time.",
         active="For {duration}s or 10 successfully broken tagged stone/ore blocks, mine 40% faster with a tool that can harvest them. This changes normal mining speed, never drops, tool tiers, durability or neighboring blocks.",
         passive="+2 armor. Gain +0.25 knockback resistance while grounded on tagged stone support.",
         weakness="-8% movement speed and -8% attack speed. Good footing rewards a deliberate pace.",
         params=dict(fraction=.4,charges=10),attrs_p=dict(armor=2),traits_p=dict(stone_knockback=.25),attrs_w=dict(speed=-.08,attack_speed=-.08)),
    dict(id="moss_one",family="dwarven",display="Moss One",scale=.7,feathers=22,impact=2,ars=(1,1),iss=1,
         powers=("mycelial_respite","living_loam","desiccation"),names=("Mycelial Respite","Living Loam","Desiccation"),cd=1100,duration=160,
         lore="Keepers of sheltered mushroom gardens, these dwarves carry the patience of deep roots. A small haven is their answer to a harsh world.",
         active="Create a stationary 3-block recovery patch for {duration}s. Every 2s, restore 1 HP to yourself and up to two allies in sight. Each cast admits three recipients total, removes Poison once per recipient, and offers at most 4 HP each (6 HP after amplification). Overlapping patches share a recovery interval.",
         passive="+2 armor. Finishing tagged mushroom food adds 1 food point and 1 saturation point, within normal limits; containers and food effects are preserved.",
         weakness="Take 25% more fire damage and move 5% slower. Shelter from flame and recover where allies can remain nearby.",
         params=dict(radius=3,targets=3,interval=40,healing=1,budget=4,final_cap=6),attrs_p=dict(armor=2),traits_p=dict(food_bonus=1,saturation_bonus=1),attrs_w=dict(speed=-.05),traits_w=dict(fire_extra=.25)),
    dict(id="crystal_one",family="dwarven",display="Crystal One",scale=.72,feathers=20,impact=2,ars=(1.05,.95),iss=1.05,
         powers=("prism_reprisal","faceted_body","fracture_lines"),names=("Prism Reprisal","Faceted Body","Fracture Lines"),cd=800,duration=120,
         lore="Gem-attuned dwarves whose composure catches the sharp edge of sorcery. A single ringing answer matters more than a storm of reflections.",
         active="For {duration}s, counter one accepted magical or projectile hit: prevent 50%, capped at 4 HP after armor and absorption. Preventing at least 1 HP answers a legal attacker within 8 blocks and sight for 2 HP. The counter is spent even without a reply; replies cannot trigger racial retaliation.",
         passive="+2 armor and 10% less classified magical damage.",
         weakness="-2 maximum HP and 20% more explosion damage. Magical explosions apply both the magical affinity and explosion penalty; avoid blast centers.",
         params=dict(budget=4,prevent_fraction=.5,reply_damage=2,reply_range=8),attrs_p=dict(armor=2),traits_p=dict(magic_reduction=.1),attrs_w=dict(health=-2),traits_w=dict(explosion_extra=.2)),
    dict(id="bovine",family="bestial",display="Bovine",scale=1.15,feathers=26,impact=2,ars=(1,1),iss=1,
         powers=("hornrush","herd_strength","heavy_appetite"),names=("Hornrush","Herd Strength","Heavy Appetite"),cd=600,duration=16,
         lore="Strong horned folk who stand together and commit with their whole weight. A Bovine's charge is a promise to follow one path to its end.",
         active="From dry ground, wind up for 0.3s and rush up to 5 blocks. The first legal body collision takes 6 HP physical damage and moderate knockback. Walls, allies and pets stop the rush. Your held weapon adds no damage.",
         passive="+2 maximum HP and +0.20 knockback resistance. Sprint 10% faster while grounded; Pehkui scale is 1.15 when installed.",
         weakness="+20% exhaustion and -8% attack speed. A committed charge has little steering; keep food for the journey.",
         params=dict(range=5,windup=6,move_ticks=10,damage=6),attrs_p=dict(health=2,kb=.2),traits_p=dict(sprint_speed=.1),attrs_w=dict(attack_speed=-.08),exhaustion=.2),
    dict(id="saurian",family="bestial",display="Saurian",scale=1,feathers=22,impact=2,ars=(1,1),iss=1,
         powers=("patient_ambush","scaled_survivor","cold_blooded"),names=("Patient Ambush","Scaled Survivor","Cold-Blooded"),cd=600,duration=100,
         lore="Watchful scaled survivors who let the world move first. Their patience prepares a close ambush; venom is another bloodline's answer.",
         active="After staying nearly still for 1s, prepare a {duration}s ambush. Your next successful primary melee hit at 90% charge adds 3 HP and Slowness I for 2s. You may move freely after arming.",
         passive="+2 armor and 15 additional seconds of air before drowning. Respiration still helps; this is finite breath, not water breathing.",
         weakness="Move 5% slower. In tagged cold biomes, attack 15% slower and take 25% more freezing damage. Leather insulation, Fire Resistance, being on fire, or a lit campfire/fire/lava within 2 blocks prevents the cold state.",
         params=dict(stationary_ticks=20,bonus=3,min_charge=.9,effect_ticks=40),attrs_p=dict(armor=2),traits_p=dict(extra_air=300),attrs_w=dict(speed=-.05),traits_w=dict(cold_attack_slow=.15,cold_freeze_extra=.25)),
    dict(id="chelon",family="bestial",display="Chelon",scale=1.05,feathers=24,impact=2,ars=(1,1),iss=1,
         powers=("shellfast","living_shell","unhurried"),names=("Shellfast","Living Shell","Unhurried"),cd=900,duration=100,
         lore="Shell-backed folk who know when to step out and when to endure. Their refuge is brief, deliberate, and carried upon their own shoulders.",
         active="Withdraw for up to {duration}s, preventing 50% of ordinary physical/projectile health damage, with a 12 HP budget. Movement is capped at 20% of walking speed. Attacks, shields, item use, spells and block interaction are suspended. Release and press again to exit. No protection from suffocation, starvation, drowning or bypass damage.",
         passive="+3 armor and 10 additional seconds of air before drowning. Normal land life and all ordinary equipment remain available.",
         weakness="-10% movement speed and -10% attack speed, including outside Shellfast. Choose a safe moment to re-enter a fight.",
         params=dict(budget=12,prevent_fraction=.5),attrs_p=dict(armor=3),traits_p=dict(extra_air=200),attrs_w=dict(speed=-.1,attack_speed=-.1)),
    dict(id="zephyr",family="faeborne",display="Zephyr",scale=.8,feathers=14,impact=3,ars=(1.15,.9),iss=1,
         powers=("crosswind","airborne_essence","scattered_form"),names=("Crosswind","Airborne Essence","Scattered Form"),cd=600,duration=8,
         lore="Air spirits gathered into delicate mortal outlines. Their ribbon-like fins catch small currents, preferring precision over a dragon's power.",
         active="Redirect yourself horizontally up to 5 blocks over {duration}s. Solid obstacles stop you. Crosswind deals no damage, grants no invulnerability, and cannot launch you upward.",
         passive="Glide on visible air-ribbon wings and take 50% less fall damage. Flap for +0.30 upward velocity every 2s; each flap costs one feather when enabled. Wind Wyrm remains the stronger powered flier.",
         weakness="-4 maximum HP and 1.40 times knockback received. Avoid exposed melee and keep room to recover your direction.",
         params=dict(range=5,move_ticks=8),traits_p=dict(fall_reduction=.5),attrs_w=dict(health=-4),wings=True,flap=40,knockback=1.4),
    dict(id="nightborn",family="undead",display="Nightborn",scale=1,feathers=20,impact=2,ars=(1,1),iss=1,
         powers=("crimson_hunt","nocturnal_senses","sun_starved"),names=("Crimson Hunt","Nocturnal Senses","Sun-Starved"),cd=900,duration=160,
         lore="Nocturnal hunters with a brief and carefully bounded hunger. The living world still offers them ordinary food, friendship, and shelter.",
         active="Hunt for {duration}s with +10% speed. Up to three 90%-charged primary melee hits feed, at least 1s apart: restore 25% of real health damage, capped at 2 HP per hit and 6 HP per cast before healing modifiers, and 6 HP restored after them. Allies, pets, villagers, undead and tagged inorganic creatures cannot feed you.",
         passive="Poison immunity and night vision in light level 7 or below. Move 15% faster at actual nighttime with at least 12 food points.",
         weakness="Receive 20% less healing and take 20% more damage in direct sunlight. A helmet, roof, night or rain shields you from direct sun. Normal meals remain useful.",
         params=dict(speed=.1,charges=3,interval=20,min_charge=.9,fraction=.25,healing=2,budget=6,final_cap=6),traits_p=dict(night_speed=.15,night_food=12),traits_w=dict(sun_extra=.2),healing=-.2,poison=True,vision="low_light"),
    dict(id="returned",family="undead",display="Returned",scale=1,feathers=24,impact=2,ars=(1,1),iss=1,
         powers=("unfinished_purpose","stubborn_remnant","imperfect_return"),names=("Unfinished Purpose","Stubborn Remnant","Imperfect Return"),cd=800,duration=200,
         lore="People sustained by a purpose left unfinished. The Returned seek the confrontation ahead; they claim no second resurrection or borrowed death-site.",
         active="Designate your latest legal living aggressor from the last 30s, within 16 blocks and sight. For {duration}s, gain 15% grounded speed while moving toward them; one 90%-charged primary melee hit adds 2 HP. No valid aggressor means no cooldown spent.",
         passive="+2 maximum HP and poison immunity. Below half health, gain +0.30 knockback resistance.",
         weakness="Receive 25% less healing. Food and potions work normally at reduced strength; this heritage does not change respawn or Reaper revival.",
         params=dict(range=16,recency_ticks=600,speed=.15,bonus=2,min_charge=.9),attrs_p=dict(health=2),traits_p=dict(low_health_knockback=.3),healing=-.25,poison=True),
    dict(id="wailer",family="undead",display="Wailer",scale=.95,feathers=18,impact=3,ars=(1.1,.95),iss=1.05,
         powers=("keening_cry","deathwatch","fraying_spirit"),names=("Keening Cry","Deathwatch","Fraying Spirit"),cd=800,duration=11,
         lore="Sorrowful spirits who warn the world before their voices break upon it. Their awareness follows nearby wounded threats, not hidden lives beyond the walls.",
         active="After a visible and audible 0.5s warning, cry into a 6-block cone with a 35-degree half-angle. Up to six threats in sight take 2 HP, Weakness I for 4s and moderate knockback. Move 30% slower during the warning. Bosses resist control; player control requires server permission and has half duration.",
         passive="Poison immunity. Once per second, sense up to three hostile creatures below half health, within 8 blocks and sight, through small owner-only target wisps.",
         weakness="-4 maximum HP and 15% more ordinary physical damage taken. Use cover and space during the cry's warning.",
         params=dict(windup=10,range=6,angle=35,targets=6,damage=2,effect_ticks=80,speed=.3),traits_p=dict(sense_range=8,sense_targets=3),attrs_w=dict(health=-4),traits_w=dict(physical_extra=.15),poison=True),
    dict(id="scaleheir",family="draconic",display="Scaleheir",scale=1.1,feathers=24,impact=1,ars=(.9,1.1),iss=1,
         powers=("dominion_roar","inherited_scales","demanding_blood"),names=("Dominion Roar","Inherited Scales","Demanding Blood"),cd=700,duration=100,
         lore="Grounded heirs to dragonkind, bearing scales and a steady presence. Their lineage needs neither elemental breath nor wings to stand its ground.",
         active="Ward yourself for {duration}s, preventing at most 4 HP after armor and absorption. Up to three threats within 5 blocks and sight receive Weakness I for 3s. No damage, forced targeting or boss control; player control follows server policy.",
         passive="+2 armor and +0.20 knockback resistance. This grounded lineage has no racial flight, breath weapon or elemental immunity.",
         weakness="+20% exhaustion and -8% attack speed. Good meals and measured swings sustain demanding draconic blood.",
         params=dict(budget=4,prevent_fraction=1,range=5,targets=3,effect_ticks=60),attrs_p=dict(armor=2,kb=.2),attrs_w=dict(attack_speed=-.08),exhaustion=.2),
    dict(id="wyvernkin",family="draconic",display="Wyvernkin",scale=1.08,feathers=22,impact=2,ars=(.9,1.1),iss=1,
         powers=("venom_swoop","lean_wings","exposed_membranes"),names=("Venom Swoop","Lean Wings","Exposed Membranes"),cd=700,duration=10,
         lore="Lean dragonfolk with hooked wings and a single venomous commitment. They borrow height from the landscape, then spend it on one precise swoop.",
         active="Lunge up to 3 blocks from the ground or sweep up to 5 blocks while already gliding. The first legal collision takes 5 HP physical damage and Poison I for 3s. Walls and protected bodies stop you. No weapon damage, repeated contact hits or powered ascent.",
         passive="Innate gliding wings, +1 armor and 25% less fall damage. No independent powered flap; use terrain and the occasional swoop.",
         weakness="-2 maximum HP and 15% more projectile damage taken. Cover your exposed membranes from arrows and magical projectiles.",
         params=dict(range=5,land_range=3,move_ticks=10,damage=5,effect_ticks=60),attrs_p=dict(armor=1),traits_p=dict(fall_reduction=.25),attrs_w=dict(health=-2),traits_w=dict(projectile_extra=.15),wings=True),
]

def emit_expansion(g):
    def traits(values): return {"type":"runic_races:racial_traits", "values":values}
    def attrs(values, name):
        builders={"health":g["health"],"armor":g["armor"],"kb":g["kb_resist"],"speed":g["speed"],"attack_speed":g["atk_spd"]}
        return [(k,builders[k](v,name+" "+k)) for k,v in values.items()]
    for index,r in enumerate(RACES):
        race=r["id"]; a,p,w=r["powers"]
        g["DISPLAY"][race] = r["display"]
        desc=r["active"].format(duration=f'{r["duration"]/20:g}')+f' {r["cd"]/20:g}-second cooldown.'
        active=g["bundle"](race,a,r["names"][0],desc,[
            ("cooldown_timer",g["cooldown_subpowers"](f"runic_races:{race}/{a}_cooldown_timer",r["cd"])[0]),
            ("active_ability",dict(type="runic_races:racial_ability",kind=race,cooldown_ticks=r["cd"],duration_ticks=r["duration"],parameters=r["params"]))])
        passive=attrs(r.get("attrs_p",{}),r["names"][1]);weakness=attrs(r.get("attrs_w",{}),r["names"][2])
        if r.get("traits_p"): passive.append(("mechanics",traits(r["traits_p"])))
        if r.get("traits_w"): weakness.append(("mechanics",traits(r["traits_w"])))
        if r.get("poison"): passive.append(("poison_immunity",g["imm"]("poison")))
        if r.get("water"): passive.append(("water_breathing",g["water_breathing"]()))
        if r.get("water_vision"): passive.append(("water_vision",{"type":"origins:night_vision","strength":1,"condition":{"type":"origins:submerged_in","fluid":"minecraft:water"}}))
        if r.get("vision"): passive.append(("night_vision",dict(type="origins:night_vision",strength=1,condition={"type":"runic_races:racial_environment","predicate":r["vision"]})))
        if r.get("wings"): passive += g["wings_specs"](race,p,r.get("flap",False))
        if r.get("exhaustion"): weakness.append(("exhaustion",g["exhaustion"](r["exhaustion"])))
        if r.get("healing"): weakness.append(("healing",{"type":"origins:modify_healing","modifier":{"operation":"multiply_total_multiplicative","value":r["healing"]}}))
        g["emit"](race,r["family"],g["FAMILY_ORDER"][r["family"]]*100+50+index,r["impact"],r["lore"],
                  (a,active),(p,g["bundle"](race,p,r["names"][1],r["passive"],passive)),(w,g["bundle"](race,w,r["names"][2],r["weakness"],weakness)))
        g["LANG"][f"message.runic_races.{race}.{a}"]=r["names"][0]+"!"
